project:
  type: website
  output-dir: docs

website:
  favicon: assets/images/data100_logo.png
  title: "Data 100: Principles and Techniques of Data Science"
  image: assets/images/data100_logo.png
  site-url: "https://ds100.org/course-notes/"
  repo-url: https://github.com/DS-100/course-notes
  search:
    location: sidebar
    type: textbox
  sidebar:
    style: "docked"
    logo: "assets/images/data100_logo.png"
    title: "Data 100 Course Notes"
    logo-alt: "Data 100 logo"
    tools:
      - icon: github
        href: https://github.com/DS-100/course-notes
    contents:
      - index.md
      - intro_lec/introduction.qmd
      - pandas_1/pandas_1.qmd
      - pandas_2/pandas_2.qmd
      - pandas_3/pandas_3.qmd
      - eda/eda.qmd
      - regex/regex.qmd
      - visualization_1/visualization_1.qmd
      - visualization_2/visualization_2.qmd
      - sampling/sampling.qmd
      - modeling_slr/modeling_slr.qmd
      - constant_model_loss_transformations/loss_transformations.qmd
      - ols/ols.qmd
      - case_study_HCE/case_study_HCE.qmd
      - gradient_descent/gradient_descent.qmd
      - feature_engineering/feature_engineering.qmd
      - cv_regularization/cv_reg.qmd
      - probability_1/probability_1.qmd
      - probability_2/probability_2.qmd
      - inference_causality/inference_causality.qmd
      - sql_I/sql_I.qmd
      - sql_II/sql_II.qmd
      - logistic_regression_1/logistic_reg_1.qmd
      - logistic_regression_2/logistic_reg_2.qmd
      - clustering/clustering.qmd
      - pca/pca.qmd
    
format:
  html:
    theme: cosmos
    toc: true
    toc-depth: 5
    callout-icon: false
    code-fold: false
    include-after-body: 
      - assets/scripts/a11y-fixes.html
    css:
      - assets/styles/style.css
jupyter: python3